spring:
  datasource:
    url: "jdbc:h2:tcp://localhost/~/test"
    driver-class-name: org.h2.Driver
    username: "sa"
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  mvc:
    view:
      prefix: "/WEB-INF/view/"
      suffix: ".jsp"